#pragma once

#if !defined(VK_INSTANCE_FUNCTION)
#define VK_INSTANCE_FUNCTION( fun )
#endif

VK_INSTANCE_FUNCTION(vkEnumeratePhysicalDevices)
VK_INSTANCE_FUNCTION(vkGetPhysicalDeviceProperties)
VK_INSTANCE_FUNCTION(vkGetPhysicalDeviceFeatures)
VK_INSTANCE_FUNCTION(vkGetPhysicalDeviceQueueFamilyProperties)
VK_INSTANCE_FUNCTION(vkCreateDevice)
VK_INSTANCE_FUNCTION(vkGetDeviceProcAddr)
VK_INSTANCE_FUNCTION(vkDestroyInstance)
VK_INSTANCE_FUNCTION(vkEnumerateDeviceExtensionProperties)

#if defined (VK_KHR_swapchain)
VK_INSTANCE_FUNCTION(vkGetPhysicalDeviceSurfaceSupportKHR)
VK_INSTANCE_FUNCTION(vkGetPhysicalDeviceSurfaceCapabilitiesKHR)
VK_INSTANCE_FUNCTION(vkGetPhysicalDeviceSurfaceFormatsKHR)
VK_INSTANCE_FUNCTION(vkGetPhysicalDeviceSurfacePresentModesKHR)*
VK_INSTANCE_FUNCTION(vkDestroySurfaceKHR)
#endif

VK_INSTANCE_FUNCTION(vkGetPhysicalDeviceMemoryProperties)

#if defined (FL_DEBUG)
VK_INSTANCE_FUNCTION(vkCreateDebugUtilsMessengerEXT)
VK_INSTANCE_FUNCTION(vkDestroyDebugUtilsMessengerEXT)

#undef VK_INSTANCE_FUNCTION