name: Engine Linux Build

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'CONTRIBUTING.md'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'CONTRIBUTING.md'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64]
        mode: [debug, release]

    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}

    steps:

      - uses: actions/checkout@v4
        name: Checkout

      - name: Set xmake env
        run: echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/xmake-global" >> $GITHUB_ENV

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache'
        name: Setup XMake

      - name: Update XMake Repository
        run: xmake repo --update

      - name: Configure XMake and install dependencies
        run: xmake config --arch=${{ matrix.arch }} --mode=${{ matrix.mode }} --yes

      - name: Build ${{ matrix.mode }}
        run: |
          xmake -y
      - name: Install App
        if: ${{ github.event_name == 'push' }}
        run: xmake install -vo package

      - name: "Set PACKAGE_NAME variable"
        if: ${{ github.event_name == 'push' }}
        run: echo "PACKAGE_NAME=linux_${{matrix.arch}}_${{matrix.mode}}.zip" >> $GITHUB_ENV
        shell: bash

      - name: Archive result
        uses: ihiroky/archive-action@v1
        if: ${{ github.event_name == 'push' }}
        with:
          root_dir: package
          file_path: ${{ env.PACKAGE_NAME }}
          verbose: true

      - name: Update archive as artifact
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'push' }}
        with:
          name: Linux-${{matrix.arch}}-${{matrix.mode}}
          path: ${{ env.PACKAGE_NAME }}